[build]
builder = "nixpacks"
buildCommand = "npm run build && npx prisma db push"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/"
timeout = 30
